### ISSUE TITLE
src/lib/htmshell.c doesn't compile on aarch64 Ubuntu 20.04

### ISSUE THREAD

**Issue by nathanweeks** [ucscGenomeBrowser/kent#73]
**Describe the bug**
src/lib/htmshell.c doesn't compile on an Ubuntu 20.04 aarch64 with the default gcc 9.4.0 installed by `apt install gcc`. The source file compiles successfully on Ubuntu 20.04 x86_64.

 **To Reproduce**
Launch an Ubuntu 20.04 VM (e.g., on AWS, or use an Ubuntu 20.04 container base image in a Docker / Rancher Desktop on an aarch64 macOS host), clone the repository (tested with commit [36ae2af](https://github.com/ucscGenomeBrowser/kent/commit/36ae2af1b2a0d3199292a8b2dfcee385855f140d)), and attempt to compile:

```
$ git clone https://github.com/ucscGenomeBrowser/kent.git
$ cd kent
make -C src/lib
...
htmshell.c: In function ‘htmlVaBadRequestAbort’:
htmshell.c:714:28: error: invalid operands to binary != (have ‘va_list’ {aka ‘__va_list’} and ‘void *’)
  714 | if (format != NULL && args != NULL)
      |                            ^~
make: *** [../inc/common.mk:533: htmshell.o] Error 1 
```

**Comment by christopherLee1** [comment]
Hi Nathan,

This is indeed a valid bug. We are upgrading some of our infrastructure (including upgrading our gcc version) in the coming weeks, and we expect to find a few of these types of bugs very soon, which we will probably fix in a single commit.

We'll update this ticket once that's done but in the meantime feel free to maintain your own copy locally or submit a pull request.

**Comment by z4668640** [comment]
> 嗨，内森，
> 
> 这确实是一个有效的错误。我们将在未来几周内升级我们的一些基础设施（包括升级我们的 gcc 版本），我们预计很快就会发现一些此类错误，我们可能会在一次提交中修复这些错误。
> 
> 完成后，我们将更新此票证，但与此同时，请随时在本地维护自己的副本或提交拉取请求。



> Hi Nathan,
> 
> This is indeed a valid bug. We are upgrading some of our infrastructure (including upgrading our gcc version) in the coming weeks, and we expect to find a few of these types of bugs very soon, which we will probably fix in a single commit.
> 
> We'll update this ticket once that's done but in the meantime feel free to maintain your own copy locally or submit a pull request.

This bug has not been fixed yet. Is there a version that does not display this error?

**Comment by matthewspeir** [comment]
Hello, @z4668640.
 
One of our engineers fixed this in a recent commit, 8b044625d9cdd9dfaec89ff32d0ecb069b7c0565. 

If you find similar bugs in the future, we can accept pull requests through Github.

Matthew Speir
UCSC Genome Browser, User Support
